export { default as Home } from './Home.jsx';
export { default as AllJobs } from './AllJobs.jsx'
export { default as JobDetailPage } from './JobDetailPage.jsx'
export { default as Homepage } from './Homepage.jsx'
export { default as EmployeHome } from './Employee/EmployeHome.jsx'
export { default as EmployeeAppliedJobs } from './Employee/EmployeeAppliedJobs.jsx'
export { default as ProfileCard } from './Employee/ProfileCard.jsx'
export { default as Aboutus } from './Aboutus.jsx'
export { default as AdminHome } from './adminPages/AdminHome.jsx'
export {default as ContactUs} from './ContactUs.js'